from map import ALL_MAZES
FPS = 60
BG_COLOR = (245,0,70)
WALL_SIZE = 50
BRICK_COLOR = (0,0,0)
MAX_ROWS = max(len(maze) for maze in ALL_MAZES)
MAX_COLS = max(len(maze[0]) for maze in ALL_MAZES)
HEIGHT = MAX_ROWS * WALL_SIZE 
WIDTH = MAX_COLS * WALL_SIZE
RUNNER_COLOR = (0,245,70)
END_START_COLOR = (0,0,255)
RUNNER_SIZE = WALL_SIZE
RUNNER_SPEED = 5